# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a387d16987aacb65e705b9f52fac0e7e375c87d1b040ca603fbfd6e25eee64cb2af776da772e554f0a6f795dc2f0c9b29dc4fe8e544350b04d582208088dbe35

test:
  secret_key_base: 8da9dee712b25eb7d6c6ea2e9be8c20ba1371d447b03fc3aff98fef95ac3e0955429267f95b9779e178472db705597db7838ac816f05e84da97911ab97a9d3e2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
